version: '3'
services:
  app:
    build: .
    ports:
      - "80:3000"
  mongo:
    image: "mongo"
    ports: 
      - 2717:27017
    volumes:
      - tourdeapp-data:/data/db

volumes:
  tourdeapp-data: